name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: build-linux-no-test
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo "Hello World"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install abysl for python
        run: pip install absl-py
      - name: Install protobuf compiler for python
        run: pip install python-protobuf
      - name: Install protobuf native compiler
        run: sudo apt-get install protobuf-compiler
      - name: Build linux
        run: |
           set -e
           set -x
           mkdir -p linux_build
           cd linux_build
           cmake .. -DFIREBASE_CPP_BUILD_TESTS=OFF -DFIREBASE_FORCE_FAKE_SECURE_STORAGE=ON "$@"
           cpus=$(nproc --all)
           cmake --build . -- -j $cpus
